[font]
# normal = {family = "Monaspace Krypton Var", style = "Regular"}
size = 13.0

[[font.normal]]
family = "Monaspace Krypton Var"
style = "Regular"

[[font.bold]]
family = "Monaspace Krypton Var"
style = "ExtraBold"

[[font.italic]]
family = "Monaspace Krypton Var"
style = "MediumItalic"

[[font.bold_italic]]
family = "Monaspace Krypton Var"
style = "ExtraBoldItalic"

[font.features]
"Monaspace Krypton Var" = ["+calt", "+ss01", "+ss02", "+ss03", "+ss04", "+ss05", "+ss06", "+ss07", "+ss08", "+ss09", "+liga"]
