#!/usr/bin/env python
import readline
while True:
    try:
        buf = input()
    except EOFError:
        break
    if buf:
        v = int(eval(str(buf)))
        print('0x{:x}\t0{:o}\t{:d}'.format(v, v, v))
